### ISSUE TITLE
bug del profilo per simone

### ISSUE THREAD

**Issue by ceribbo** [ClothAppProject/ClothAppAndroid#27]
- [x] item name nell'adattatore delle immagini caricate
- [x] aggiornamento cuori quando torni dall'image fragment
- [x] eliminare campi che non sono presenti nel fragment dell'info
- [x] immagine del profilo sempre personale nel menu laterale

**Comment by c-simone** [comment]
This is done now:
- [x] aggiornamento cuori quanto torni dall'image fragment
- [x] immagine del profilo sempre personale nel menu laterale

**Comment by c-simone** [comment]
This is done now:
- [x] item name nell'adattatore delle immagini caricate
- [x] eliminare campi che non sono presenti nel fragment dell'info

**Comment by c-simone** [comment]
Closing this issue.
